-- Hyprland config, lua format (hyprlang/.conf was deprecated in 0.55, removed in 0.57).
-- Reference: https://wiki.hypr.land/Configuring/Start/
-- API stubs for LSP autocomplete live in /usr/share/hypr/stubs (see .luarc.json).

-- Hardware-detected settings, generated by install.sh (see .gitignore).
-- pcall: a missing module would otherwise abort the rest of this file.
pcall(require, "hardware")

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- Catch-all safety net: lights up any monitor at its preferred mode before the
-- layout script runs and handles unknown externals. scripts/monitors.sh then
-- refines this (forces native res on known externals, toggles the laptop panel).
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})


---------------------
---- MY PROGRAMS ----
---------------------

local terminal    = "kitty"
local fileManager = "dolphin"
local menu        = "wofi --show drun"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("swaync")
    hl.exec_cmd("udiskie")
    hl.exec_cmd("hyprpolkitagent")
    hl.exec_cmd("systemctl --user start pipewire")
    hl.exec_cmd("systemctl --user start wireplumber")
    hl.exec_cmd("systemctl --user start xdg-desktop-portal")
    hl.exec_cmd("systemctl --user start xdg-desktop-portal-hyprland")
    hl.exec_cmd("hypridle")
    -- Dynamic monitor layout (Framework 13 / desktop / external displays) + hotplug watcher.
    hl.exec_cmd("~/.config/hypr/scripts/monitors.sh")
    hl.exec_cmd("~/.config/hypr/scripts/monitor-watch.sh")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    -- Process user XDG autostart entries (1Password, Synology Drive, etc.).
    -- -s restricts to ~/.config/autostart so system-wide /etc/xdg/autostart KDE entries are ignored.
    hl.exec_cmd("dex -a -s ~/.config/autostart")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 10,

        border_size = 2,

        col = {
            active_border   = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding = 10,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        blur = {
            enabled  = true,
            size     = 3,
            passes   = 1,

            vibrancy = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },

    -- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
    dwindle = {
        -- pseudotile removed in Hyprland 0.55 -- toggle per-window via hl.dsp.window.pseudo()
        -- (mainMod + P below) or a `pseudo = true` window rule.
        preserve_split = true, -- You probably want this
    },

    -- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
    master = {
        new_status = "master",
    },

    misc = {
        force_default_wallpaper = 0,    -- disable anime mascot fallback (we use hyprpaper)
        disable_hyprland_logo   = true, -- no random hyprland logo overlay
        mouse_move_enables_dpms = true,
        key_press_enables_dpms  = true,
    },
})

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })

hl.animation({ leaf = "windows",     enabled = true, speed = 7,  bezier = "myBezier" })
hl.animation({ leaf = "windowsOut",  enabled = true, speed = 7,  bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "border",      enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 8,  bezier = "default" })
hl.animation({ leaf = "fade",        enabled = true, speed = 7,  bezier = "default" })
hl.animation({ leaf = "workspaces",  enabled = true, speed = 6,  bezier = "default" })


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us,se",
        kb_variant = "",
        kb_model   = "",
        kb_options = "grp:win_space_toggle",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

-- See https://wiki.hypr.land/Configuring/Basics/Binds/
local mainMod = "SUPER" -- the "Windows" key (META is an alias for the same modmask)

hl.bind(mainMod .. " + Q",   hl.dsp.exec_cmd("~/.config/hypr/scripts/confirm-close.sh"))
hl.bind(mainMod .. " + TAB", hl.dsp.exec_cmd("~/.config/wofi/wofi-window.sh"))
hl.bind(mainMod .. " + M",   hl.dsp.exec_cmd("wlogout -b 5"))
hl.bind(mainMod .. " + E",   hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V",   hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + D",   hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P",   hl.dsp.window.pseudo())          -- dwindle
hl.bind(mainMod .. " + J",   hl.dsp.layout("togglesplit"))    -- dwindle

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness (the old `bindel` = locked + repeating)
hl.bind("XF86AudioRaiseVolume",  hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"),    { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume",  hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),    { locked = true, repeating = true })
hl.bind("XF86AudioMute",         hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",      hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl s 10%+"),                         { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"),                         { locked = true, repeating = true })

-- Screenshot region to clipboard
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd('grim -g "$(slurp)" - | wl-copy'))

-- Screenshot full screen to clipboard
hl.bind("Print", hl.dsp.exec_cmd("grim - | wl-copy"))

-- Clipboard history
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("cliphist list | wofi --dmenu | cliphist decode | wl-copy"))

-- Bluetooth TUI
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(terminal .. " -e bluetuith"))

-- WiFi TUI
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(terminal .. " -e nmtui"))

-- Notification center toggle
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("swaync-client -t -sw"))


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Ignore maximize requests from all apps.
hl.window_rule({
    name           = "suppress-maximize-events",
    match          = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    match = { class = "(?i).*kcalc.*" },
    float = true,
})

hl.window_rule({
    match = {
        class = [[^(org\.remmina\.Remmina)$]],
        title = [[^(Remmina Remote Desktop Client)$]],
    },
    float = true,
})
