- hosts: all 
  become: yes
  vars:
    nix_user: "{{ ansible_user }}"
    dotfiles_repo: "https://github.com/wfaler/dotfiles.git"  
    dotfiles_dir: "/home/{{ nix_user }}/dotfiles"
    nix_zsh_path: "/home/{{ nix_user }}/.nix-profile/bin/zsh"
    alacritty_repo: "https://github.com/alacritty/alacritty.git"
    alacritty_dir: "/home/{{ nix_user }}/dev/alacritty"
    user_home: "/home/{{ nix_user }}"
    docker_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
    install_gui_apps: true
    flatpak_apps:
      - com.spotify.Client
      - com.discordapp.Discord 
      - com.slack.Slack 
      - ch.protonmail.protonmail-bridge 
      - com.github.tchx84.Flatseal
      - com.google.Chrome 
      - com.brave.Browser 
      - com.calibre_ebook.calibre 
      - com.jetbrains.DataGrip
      - com.jetbrains.IntelliJ-IDEA-Ultimate
      - com.ktechpit.whatsie
      - com.obsproject.Studio
      - com.protonvpn.www
      - com.todoist.Todoist
      - com.usebruno.Bruno
      - io.github.getnf.embellish 
      - org.darktable.Darktable 
      - org.flameshot.Flameshot 
      - org.gnome.Evolution
      - org.keepassxc.KeePassXC 
      - org.signal.Signal 
      - us.zoom.Zoom
      - md.obsidian.Obsidian
      - org.audacityteam.Audacity  
      - org.audacityteam.Audacity.Codecs
  tasks:
    ## start Apt and Debian/Ubuntu/PopOS specific install
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Consider the cache valid for 1 hour
    - name: Install apt dependencies
      apt:
        name: 
          - autoconf 
          - build-essential 
          - patch
          - libssl-dev
          - libyaml-dev
          - stow
          - clang
          - xclip
          - libreadline6-dev
          - zlib1g-dev
          - libgmp-dev
          - libncurses5-dev
          - libffi-dev
          - libgdbm6
          - uuid-dev
          - libfontconfig-dev
          - cifs-utils
          - fontconfig 
          - libfontconfig-dev
          - wireguard
          - wireguard-tools
          - curl
          - git
          - xz-utils
          - ca-certificates
        state: present
    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Create dev directory
      become_user: "{{nix_user}}"
      file:
        path: "{{user_home}}/dev"
        state: directory
        mode: '0755'

    - name: Download and store the Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker.gpg
        mode: '0644'

    - name: Dearmor GPG key
      ansible.builtin.shell: gpg --dearmor < /tmp/docker.gpg > /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ docker_arch }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Update apt cache
      apt:
        update_cache: yes          
    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin 
          - docker-compose-plugin
        state: present
    # end Apt stuff and Debian/Ubuntu/PopOS specific install
    - name: Ensure Docker service is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes
    - name: Add nix_user to docker group
      user:
       name: "{{ nix_user }}"
       groups: docker
       append: yes
    - name: Create .envrc file
      become_user: "{{ nix_user }}"
      file:
        path: "{{ user_home }}/.envrc"
        state: touch
        modification_time: preserve
        access_time: preserve
    - name: Create .config directory
      become_user: "{{ nix_user }}"
      file:
        path: "{{ user_home }}/.config"
        state: directory
        mode: '0755'
    - name: Clone dotfiles repository
      become_user: "{{ nix_user }}"
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_dir }}"
        version: main  
        update: no 
      register: git_clone
    - name: Run stow in dotfiles directory
      become_user: "{{ nix_user }}"
      command: stow .
      args:
        chdir: "{{ dotfiles_dir }}"
      when: git_clone.changed 
    - name: Download Nix install script
      get_url:
        url: https://nixos.org/nix/install
        dest: /tmp/nix-install.sh
        mode: '0755'
    - name: Run Nix install script
      command: sh /tmp/nix-install.sh --daemon
      args:
        creates: /nix/store
    - name: Add Nix to PATH for all users
      lineinfile:
        path: /etc/profile
        line: '. /etc/profile.d/nix.sh'
        create: yes
    - name: Reload shell configuration
      shell: source /etc/profile
    - name: Verify Nix installation
      command: /nix/var/nix/profiles/default/bin/nix --version
      register: nix_version
      changed_when: false
    - name: Display Nix version
      debug:
        var: nix_version.stdout
    - name: Add Home Manager channel
      become_user: "{{ nix_user }}"
      command: nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
      args:
        creates: "/home/{{ nix_user }}/.nix-channels"
    - name: Update Nix channels
      become_user: "{{ nix_user }}"
      command: nix-channel --update
      register: channel_update
      changed_when: "'error' not in channel_update.stderr"

    - name: Install Home Manager
      become_user: "{{ nix_user }}"
      shell: |
        nix-shell '<home-manager>' -A install || true
      args:
        executable: /bin/bash
        creates: "/home/{{ nix_user }}/.config/home-manager"

    - name: Run Home Manager switch allowing unfree packages
      become_user: "{{ nix_user }}"
      shell: |
        export NIXPKGS_ALLOW_UNFREE=1 && \
        {{user_home}}/.nix-profile/bin/home-manager switch
      args:
        executable: /bin/bash
      register: hm_switch
      changed_when: "'No changes' not in hm_switch.stdout"
    - name: Add Flathub repository
      become: no
      command: flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      changed_when: false
    - name: Install Flatpak applications
      become: no
      flatpak:
        name: "{{ item }}"
        state: present
        remote: flathub
        method: user
      loop: "{{ flatpak_apps }}"
      when: install_gui_apps | default(false) | bool
    - name: Install stable Rust using rustup
      become_user: "{{ nix_user }}"
      shell: |
        . "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" && \
        rustup default stable
      args:
        executable: /bin/bash
        creates: "/home/{{ nix_user }}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu"
      when: install_gui_apps | default(false) | bool
 
    - name: Clone Alacritty repository
      become_user: "{{ nix_user }}"
      git:
        repo: "{{ alacritty_repo }}"
        dest: "{{ alacritty_dir }}"
        version: master
        depth: 1
      register: alacritty_clone
      when: install_gui_apps | default(false) | bool
 
    - name: Build and install Alacritty
      become_user: "{{ nix_user }}"
      shell: |
        cargo build --release
      args:
        chdir: "{{ alacritty_dir }}"
      when: alacritty_clone.changed and (install_gui_apps | default(false) | bool)
    - name: Create Alacritty desktop entry
      become: yes
      copy:
        dest: "/usr/share/applications/alacritty.desktop"
        content: |
          [Desktop Entry]
          Name=Alacritty
          Comment=A fast, cross-platform terminal emulator
          Exec=/home/{{ nix_user }}/.cargo/bin/alacritty
          Icon=alacritty
          Type=Application
          Categories=Utility;TerminalEmulator;
          Terminal=false
        mode: '0644'
      when: install_gui_apps | default(false) | bool
 
    - name: Copy Alacritty icon
      become: yes
      copy:
        src: "{{ alacritty_dir }}/extra/logo/alacritty-term.svg"
        dest: "/usr/share/icons/hicolor/scalable/apps/alacritty.svg"
        mode: '0644'
        remote_src: yes
      when: install_gui_apps | default(false) | bool
 
    - name: Run mise in user's home folder
      become_user: "{{ nix_user }}"
      shell: |
        . "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" && \
        ~/.nix-profile/bin/mise install
      args:
        chdir: "{{ user_home }}"
        executable: /bin/bash

    - name: Install SDKMAN for nix_user
      become_user: "{{ nix_user }}"
      shell: |
        curl -s "https://get.sdkman.io" | bash
      args:
        creates: "/home/{{ nix_user }}/.sdkman"
      register: sdkman_install

    - name: Source SDKMAN in .bashrc
      become_user: "{{ nix_user }}"
      lineinfile:
        path: "/home/{{ nix_user }}/.bashrc"
        line: '[[ -s "/home/{{ nix_user }}/.sdkman/bin/sdkman-init.sh" ]] && source "/home/{{ nix_user }}/.sdkman/bin/sdkman-init.sh"'
        state: present
      when: sdkman_install.changed
    - name: Add zsh to /etc/shells
      ansible.builtin.lineinfile:
        path: /etc/shells
        line: "/home/{{nix_user}}/.nix-profile/bin/zsh"
        state: present
    - name: Set zsh as default shell for nix_user
      ansible.builtin.user:
        name: "{{ nix_user }}"
        shell: "/home/{{ nix_user }}/.nix-profile/bin/zsh"
